export const ADD_DEVICE = 'ADD_DEVICE';
export const REMOVE_DEVICE = 'REMOVE_DEVICE';
export const UPDATE_DEVICE = 'UPDATE_DEVICE';

export const CHANGE_SETTING = 'CHANGE_SETTING';

export const ADD_DEVICE_NAME = 'ADD_DEVICE_NAME';
export const REMOVE_DEVICE_NAME = 'REMOVE_DEVICE_NAME';
export const UPDATE_DEVICE_NAME = 'UPDATE_DEVICE_NAME';
